#! /bin/bash

FROMFILE=$1
TOFILE=$2

if [ ! $# -eq 2 ];then
	echo "USAGE: COMMAND FROMFILE TOFILE"
	exit 1
fi

YEAR=`cut -b1-4 $FROMFILE &>T.YEAR`
MONTH=`cut -b5-6 $FROMFILE &>T.MONTH`
DAY=`cut -b7-8 $FROMFILE &>T.DAY`
HOUR=`cut -b9-10 $FROMFILE &>T.HOUR`
MYUID=`cut -f2 $FROMFILE &>T.MYUID`
WORD=`cut -f3 $FROMFILE &>T.WORD`
RANK=`cut -f4 $FROMFILE &>T.RANK`
CLICKSEQ=`cut -f5 $FROMFILE &>T.CLICKSEQ`
URL=`cut -f6 $FROMFILE &>T.URL`

paste -d'\t' T.YEAR T.MONTH T.DAY T.HOUR T.MYUID T.WORD T.RANK T.CLICKSEQ T.URL &>$TOFILE

rm -rf T.YEAR T.MONTH T.DAY T.HOUR T.MYUID T.WORD T.RANK T.CLICKSEQ T.URL 
